<?php
$lang['home_maintext']      = "Sljedeća generacija elementary OS-a je ovdje. Lagan i prelijep. Nove aplikacije. Prerađen izgled. Navedite cijenu ili preuzmite besplatno"

$lang['home_download']      = "Download";
$lang['home_payment']       = "Plaćanje";
$lang['home_amount']        = "Količina";  // Amount of money
$lang['home_method']        = "Metoda";  // Method of payment
$lang['home_processor']     = "Procesor";
$lang['home_creditcard']    = "Kreditna kartica";
$lang['home_direct']        = "Direktno"; // Direct download (via HTTP)
$lang['home_luna_free']     = "Besplatno preuzmi Luna izdanje";
$lang['home_elementary_is'] = "elementary je:";
$lang['home_point1']        = "Vođen od strane zajednice.";
$lang['home_expl1']         = "elementary ima jedan cilj: pružanje najboljeg mogućeg iskustva našoj zajednici. Vodi nas želja da budemo bolji, ne da nas više plaćaju. Kontributori nisu vođeni profitom, nego svrhom.";
$lang['home_point2']        = "Transparentan i otvoren.";
$lang['home_expl2']         = "Vjerujemo u moć optvorenog koda i globalne kolaboracije. Ovo znači da svako može da preuzme, koristi, modifikuje i učestvuje u kodu sa ciljem pretvaranja ideja u stvarnost. Kod je kreiran u otvorenosti, što znači da je pregledan, dorađen i modifikovan od strane desetine hiljada programera širom svijeta. Kao takav, postaje vaš operativni sistem.";
$lang['home_point3']        = "Prelijep i koristan.";
$lang['home_expl3']         = "elementary je izrađen od strane dizajnera i programera koji vjeruju da bi računari trebali da budu jednostavni, zabavni i prelijepi. Kada stavljamo dizaj na prvo mjestu, osiguravamo se da ne kompromizujemo kvalitetu i korisnost.";
$lang['home_point4']        = "Moderno računarstvo.";
$lang['home_expl4']         = "elementary OS je besplatna zamjena za Windows na PC-u i OS X na Mac-u. Dolazi sa svime što biste očekivali, kao što je brz web pretraživač i prodavnica sa aplikacijama koja sadrži hiljade aplikacija. Povrh toga, dolazi i sa još nekim stvarima koje možda niste očekivali, poput besplatnih nadogradnji i bez ijednog poznatog virusa.";
$lang['home_point5']        = "Brz";
$lang['home_expl5']         = "Luna je od početka dizajnirana da bude lagana. Brzo se pali, prijava je instantna, i koristi minimalno resursa tako da i vaše aplikacije doživljavaju porast u brzini. A sa Lunom, takođe dobijate i softver Linux fondacije koji se koristi i u svjetski najbržim super-računarima.";
$lang['home_point6']        = "Prepun mogućnosti";
$lang['home_expl6']         = "Kada instalirate elementary, ne instalirate samo operativni sistem. Instalirate i odabrane aplikacije prilagođene za ovaj operativni sistem koje vam omogućavaju da odmah krenete sa poslom. Lagano pretražujte internet, pregledajte mail-ove, slušajte muziku i savladavajte svakodnevne zadatke.";
$lang['home_app1']          = "Pretražujte po albumima, pravite plejliste, ocjenjujte pjesme i pronađite slične pjesme.";
$lang['home_app2']          = "Pretražujte internet uz brzinu rendering motora koji koriste i Google Chrome i Apple Safari.";
$lang['home_app3']          = "Konektujte se sa Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! i još mnogo drugih servisa.";
$lang['home_app4']          = "Pregledajte više korisničkih računa, dobite desktop notifikacije i čitajte vaš mail u obliku razgovora..";
$lang['home_app5']          = "Importujte, organizujte i uredite fotografije. Napravite slideshow. Podijelite na Facebook-u ili Flickr-u.";
$lang['home_app6']          = "Ostanite uvijek na najnovijem softveru. Dobijte nadogradnje instantno, zauvijek i besplatno.";
$lang['home_point7']        = "U potpunosti dostupan";
$lang['home_expl7']         = "Različiti tipovi ljudi su učestvovali u izradi elementary OS-a, tako da nije iznenađenje što je Luna napravljena sa tim u glavi. U osnovi je opremljena aplikacijama i proširenjima za one sa oštećenim vidom ili sluhom.";
$lang['home_point8']        = "Sigurna";
$lang['home_expl8']         = "Luna je napravljena na temelju Linux-a (softvera koji pokreće Minstarstvo odbrane SAD-a, Državnu banku Kine i druge). Nema poznatih virusa za ovu platformu, što znači da vam nije potreban antivirus koji će usporiti vaš sistem. Luna dobija sigurnosne nadogradnje čim se sazna za problem, što znači da nije potrebno čekanje da biste dobili najsigurniji sistem.";
$lang['home_point9']        = "100% besplatan i otvoren";
$lang['home_expl9']         = "elementary OS je u potpunosti besplatan i ima potpuno otvorene licence. Nema skupocjenih naplata, zbunjujućih pravila koja morate da poštujete, probnog razdoblja ili restriktivne zaštite protiv kopiranja. Lunu možete da instalirate na koliko god želite računara, kao i da date kopiju vašim prijateljima, i sve to u potpunosti besplatno.";
$lang['home_point10']       = "Spreman za aplikacije";
$lang['home_expl10']        = "elementary OS dolazi sa ugrađenom trgovinom za aplikacije, popunjenom sa hiljadama besplatnih aplikacija. Brzo pronađite ono što vam treba i ne morate da se brinete o malveru sa interneta prilikom procesa instalacije.";
$lang['home_whatis']        = "Šta je"; // Whole sentence reads "what is elementary OS?"
